name: CI - Build and Scan

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build_and_scan:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write
        token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set lowercase repo owner
        run: echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image (GHCR)
        run: |
          IMAGE="ghcr.io/${OWNER_LC}/secure-cicd"
          TAG="${GITHUB_SHA}"
          docker build -t "${IMAGE}:${TAG}" -t "${IMAGE}:latest" .
          docker push "${IMAGE}:${TAG}"
          docker push "${IMAGE}:latest"

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      - name: Cosign sign image
        env: 
            COSIGN_EXPERIMENTAL: true
            run: | 
              IMAGE="ghcr.io/${OWNER_LC}/secure-cicd"
              cosign sign --yes "${IMAGE}:${GITHUB_SHA}"

      - name: Trivy scan (fail on HIGH / CRITICAL)
        uses: aquasecurity/trivy-action@0.22.0
        with:
          image-ref: "ghcr.io/${{ env.OWNER_LC }}/secure-cicd:${{ github.sha }}"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          severity: "HIGH,CRITICAL"
          scanners: "vuln"